In [ ]:
from google.colab import files
uploaded = files.upload()

Saving Adelaide_Data.csv to Adelaide_Data.csv

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving Perth_Data.csv to Perth_Data.csv

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving Sydney_Data.csv to Sydney_Data.csv

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving Tasmania_Data.csv to Tasmania_Data.csv

In [ ]:
#IMPORT LIBRARIES
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split, GridSearchCV, cross_val_score
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error

In [ ]:
#ADELAIDE DATASET

In [ ]:
#LOAD DATASET
df = pd.read_csv("Adelaide_Data.csv")

df.head()

,316.5855,223.9277,182.3434,551.5497,7.8641,243.1339,361.0877,115.9284,78.6087,468.3799,...,82322.0277,98069.1011,86578.633,93016.4133,63145.1829,98353.1952,80225.139,98447.2846,97570.2225,1370374.145
0,530.3136,68.7031,31.5983,175.2582,516.1441,63.4652,67.0954,369.4486,14.0930,375.4462,...,83920.1033,80968.0044,87108.1328,68065.1856,99061.3812,77549.1426,99013.1628,78234.4337,84633.6493,1340929.765
1,27.3967,399.0488,565.6854,394.0466,120.2245,558.1293,546.4520,27.3256,314.1051,235.9476,...,97358.7395,93437.7170,69940.2554,92864.1192,60887.8095,72306.6556,81151.1515,83030.9726,94779.6131,1352031.511
2,346.1526,59.6375,226.2742,280.9095,402.2161,218.7181,207.0407,339.5676,0.0000,0.0000,...,80399.3841,89349.6141,85048.3860,70038.2271,92797.3569,97653.8121,74903.3740,71690.6549,96220.4768,1396754.375
3,317.9144,551.8542,335.4745,40.0240,316.6285,365.6434,416.3060,562.1028,211.3577,143.1255,...,97088.1761,81187.3982,63591.6729,92418.1977,82454.8256,97091.7749,85937.5437,66823.1572,93683.0996,1355708.577
4,370.1551,438.7171,222.3375,153.1610,429.7656,478.7805,303.1690,448.9657,98.8592,29.9884,...,97335.9836,70670.4876,57081.2420,86038.3420,83643.1803,97737.5596,85684.3216,57476.9499,85025.9075,1308546.042

In [ ]:
df = pd.read_csv("Adelaide_Data.csv", header=None)

In [ ]:
df.head()

,0,1,2,3,4,5,6,7,8,9,...,39,40,41,42,43,44,45,46,47,48
0,316.5855,223.9277,182.3434,551.5497,7.8641,243.1339,361.0877,115.9284,78.6087,468.3799,...,82322.0277,98069.1011,86578.6330,93016.4133,63145.1829,98353.1952,80225.1390,98447.2846,97570.2225,1370374.145
1,530.3136,68.7031,31.5983,175.2582,516.1441,63.4652,67.0954,369.4486,14.0930,375.4462,...,83920.1033,80968.0044,87108.1328,68065.1856,99061.3812,77549.1426,99013.1628,78234.4337,84633.6493,1340929.765
2,27.3967,399.0488,565.6854,394.0466,120.2245,558.1293,546.4520,27.3256,314.1051,235.9476,...,97358.7395,93437.7170,69940.2554,92864.1192,60887.8095,72306.6556,81151.1515,83030.9726,94779.6131,1352031.511
3,346.1526,59.6375,226.2742,280.9095,402.2161,218.7181,207.0407,339.5676,0.0000,0.0000,...,80399.3841,89349.6141,85048.3860,70038.2271,92797.3569,97653.8121,74903.3740,71690.6549,96220.4768,1396754.375
4,317.9144,551.8542,335.4745,40.0240,316.6285,365.6434,416.3060,562.1028,211.3577,143.1255,...,97088.1761,81187.3982,63591.6729,92418.1977,82454.8256,97091.7749,85937.5437,66823.1572,93683.0996,1355708.577

In [ ]:
df.shape

(71999, 49)

In [ ]:
columns = (
    [f"X{i}" for i in range(1,17)] +
    [f"Y{i}" for i in range(1,17)] +
    [f"P{i}" for i in range(1,17)] +
    ["Powerall"]
)

df.columns = columns

In [ ]:
print(df.columns)

Index(['X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X7', 'X8', 'X9', 'X10', 'X11',
       'X12', 'X13', 'X14', 'X15', 'X16', 'Y1', 'Y2', 'Y3', 'Y4', 'Y5', 'Y6',
       'Y7', 'Y8', 'Y9', 'Y10', 'Y11', 'Y12', 'Y13', 'Y14', 'Y15', 'Y16', 'P1',
       'P2', 'P3', 'P4', 'P5', 'P6', 'P7', 'P8', 'P9', 'P10', 'P11', 'P12',
       'P13', 'P14', 'P15', 'P16', 'Powerall'],
      dtype='object')

In [ ]:
df.head()

,X1,X2,X3,X4,X5,X6,X7,X8,X9,X10,...,P8,P9,P10,P11,P12,P13,P14,P15,P16,Powerall
0,316.5855,223.9277,182.3434,551.5497,7.8641,243.1339,361.0877,115.9284,78.6087,468.3799,...,82322.0277,98069.1011,86578.6330,93016.4133,63145.1829,98353.1952,80225.1390,98447.2846,97570.2225,1370374.145
1,530.3136,68.7031,31.5983,175.2582,516.1441,63.4652,67.0954,369.4486,14.0930,375.4462,...,83920.1033,80968.0044,87108.1328,68065.1856,99061.3812,77549.1426,99013.1628,78234.4337,84633.6493,1340929.765
2,27.3967,399.0488,565.6854,394.0466,120.2245,558.1293,546.4520,27.3256,314.1051,235.9476,...,97358.7395,93437.7170,69940.2554,92864.1192,60887.8095,72306.6556,81151.1515,83030.9726,94779.6131,1352031.511
3,346.1526,59.6375,226.2742,280.9095,402.2161,218.7181,207.0407,339.5676,0.0000,0.0000,...,80399.3841,89349.6141,85048.3860,70038.2271,92797.3569,97653.8121,74903.3740,71690.6549,96220.4768,1396754.375
4,317.9144,551.8542,335.4745,40.0240,316.6285,365.6434,416.3060,562.1028,211.3577,143.1255,...,97088.1761,81187.3982,63591.6729,92418.1977,82454.8256,97091.7749,85937.5437,66823.1572,93683.0996,1355708.577

In [ ]:
#input and output columns
position_cols = [f"X{i}" for i in range(1, 17)] + [f"Y{i}" for i in range(1, 17)]
target_col = "Powerall"

X = df[position_cols]
y = df[target_col]

print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (71999, 32)
y shape: (71999,)

In [ ]:
#missing values
df[position_cols + [target_col]].isnull().sum()

X1          0
X2          0
X3          0
X4          0
X5          0
X6          0
X7          0
X8          0
X9          0
X10         0
X11         0
X12         0
X13         0
X14         0
X15         0
X16         0
Y1          0
Y2          0
Y3          0
Y4          0
Y5          0
Y6          0
Y7          0
Y8          0
Y9          0
Y10         0
Y11         0
Y12         0
Y13         0
Y14         0
Y15         0
Y16         0
Powerall    0
dtype: int64

In [ ]:
#Split into training and testing data
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print("Training samples:", X_train.shape[0])
print("Testing samples:", X_test.shape[0])

Training samples: 57599
Testing samples: 14400

In [ ]:
#Train the Random Forest Regression model
from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(
    n_estimators=100,
    random_state=42,
    n_jobs=-1
)

rf.fit(X_train, y_train)

RandomForestRegressor(n_jobs=-1, random_state=42)

In [ ]:
#Predict the model
y_pred = rf.predict(X_test)

In [ ]:
#Evaluate using MAE and RMSE
from sklearn.metrics import mean_absolute_error, mean_squared_error
import numpy as np

mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))

print("MAE:", mae)
print("RMSE:", rmse)

MAE: 16661.914406769265
RMSE: 23588.4105599516

In [ ]:
#Hyperparameter Tuning
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestRegressor

param_grid = {
    "n_estimators": [50, 100],
    "max_depth": [10, None],
    "min_samples_split": [2, 5]
}

grid_search = GridSearchCV(
    RandomForestRegressor(random_state=42, n_jobs=-1),
    param_grid=param_grid,
    cv=3,
    scoring="neg_mean_squared_error",
    n_jobs=-1
)

grid_search.fit(X_train, y_train)

print("Best Parameters:", grid_search.best_params_)

In [ ]:
#Evaluate tuned model
best_rf = grid_search.best_estimator_

y_pred = best_rf.predict(X_test)

from sklearn.metrics import mean_absolute_error, mean_squared_error
import numpy as np

mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))

print("Tuned MAE:", mae)
print("Tuned RMSE:", rmse)

In [ ]:
#Cross validation
from sklearn.model_selection import cross_val_score

cv_scores = cross_val_score(
    best_rf,
    X,
    y,
    cv=5,
    scoring="neg_mean_squared_error",
    n_jobs=-1
)

cv_rmse = np.sqrt(-cv_scores)

print("Cross-validation RMSE scores:", cv_rmse)
print("Mean CV RMSE:", cv_rmse.mean())

In [ ]:
#Error Analysis (Residual Distribution)
residuals = y_test - y_pred_tuned

import matplotlib.pyplot as plt

plt.figure(figsize=(6,4))
plt.hist(residuals, bins=30)
plt.title("Residual Error Distribution")
plt.xlabel("Error")
plt.ylabel("Frequency")
plt.show()

In [ ]:
#Residual Plot
plt.figure(figsize=(6,4))
plt.scatter(y_pred_tuned, residuals, alpha=0.5)
plt.axhline(0, linestyle="--")
plt.title("Residual Plot")
plt.xlabel("Predicted Powerall")
plt.ylabel("Residuals")
plt.show()

In [ ]:
#PERTH DATASET

In [ ]:
#LOAD DATASET
df_perth = pd.read_csv("Perth_Data.csv", header=None)

In [ ]:
#Assign columns
columns = (
    [f"X{i}" for i in range(1,17)] +
    [f"Y{i}" for i in range(1,17)] +
    [f"P{i}" for i in range(1,17)] +
    ["Powerall"]
)

df_perth.columns = columns

In [ ]:
#input and output columns
position_cols = [f"X{i}" for i in range(1,17)] + [f"Y{i}" for i in range(1,17)]
target_col = "Powerall"

X = df_perth[position_cols]
y = df_perth[target_col]

In [ ]:
#missing values
data = df_perth[position_cols + [target_col]].dropna()

X = data[position_cols]
y = data[target_col]

print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (72000, 32)
y shape: (72000,)

In [ ]:
#Split into training and testing data
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("Training samples:", X_train.shape[0])
print("Testing samples:", X_test.shape[0])

Training samples: 57600
Testing samples: 14400

In [ ]:
#Train the Random Forest Regression model
from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(
    n_estimators=100,
    random_state=42,
    n_jobs=-1
)

rf.fit(X_train, y_train)

RandomForestRegressor(n_jobs=-1, random_state=42)

In [ ]:
#Predict the model
y_pred = rf.predict(X_test)

In [ ]:
#Evaluate using MAE and RMSE
from sklearn.metrics import mean_absolute_error, mean_squared_error
import numpy as np

mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))

print("MAE:", mae)
print("RMSE:", rmse)

MAE: 17424.559323686062
RMSE: 24151.274810701605

In [ ]:
#Hyperparameter Tuning
from sklearn.model_selection import GridSearchCV

param_grid = {
    "n_estimators": [50, 100],
    "max_depth": [10, None],
    "min_samples_split": [2, 5]
}

grid_search = GridSearchCV(
    RandomForestRegressor(random_state=42, n_jobs=-1),
    param_grid,
    cv=3,
    scoring="neg_mean_squared_error",
    n_jobs=-1
)

grid_search.fit(X_train, y_train)

print("Best Parameters:", grid_search.best_params_)

In [ ]:
#Evaluate tuned model
best_rf = grid_search.best_estimator_

y_pred_tuned = best_rf.predict(X_test)

mae_tuned = mean_absolute_error(y_test, y_pred_tuned)
rmse_tuned = np.sqrt(mean_squared_error(y_test, y_pred_tuned))

print("Tuned MAE:", mae_tuned)
print("Tuned RMSE:", rmse_tuned)

In [ ]:
#Cross validation
from sklearn.model_selection import cross_val_score

cv_scores = cross_val_score(
    best_rf,
    X,
    y,
    cv=5,
    scoring="neg_mean_squared_error",
    n_jobs=-1
)

cv_rmse = np.sqrt(-cv_scores)

print("Cross-validation RMSE scores:", cv_rmse)
print("Mean CV RMSE:", cv_rmse.mean())

In [ ]:
#Error Analysis (Residual Distribution)
residuals = y_test - y_pred_tuned

import matplotlib.pyplot as plt

plt.hist(residuals, bins=30)
plt.title("Residual Error Distribution (Perth)")
plt.xlabel("Error")
plt.ylabel("Frequency")
plt.show()

In [ ]:
#Residual Plot
plt.scatter(y_pred_tuned, residuals, alpha=0.5)
plt.axhline(0, linestyle="--")
plt.title("Residual Plot (Perth)")
plt.xlabel("Predicted Powerall")
plt.ylabel("Residuals")
plt.show()

In [ ]:
#SYDNEY DATASET

In [ ]:
#LOAD DATASET
df_sydney = pd.read_csv("Sydney_Data.csv", header=None)

In [ ]:
#Assign columns
columns = (
    [f"X{i}" for i in range(1,17)] +
    [f"Y{i}" for i in range(1,17)] +
    [f"P{i}" for i in range(1,17)] +
    ["Powerall"]
)

df_sydney.columns = columns

In [ ]:
#input and output columns
position_cols = [f"X{i}" for i in range(1,17)] + [f"Y{i}" for i in range(1,17)]
target_col = "Powerall"

X = df_sydney[position_cols]
y = df_sydney[target_col]

In [ ]:
#missing values
data = df_sydney[position_cols + [target_col]].dropna()

X = data[position_cols]
y = data[target_col]

print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (72000, 32)
y shape: (72000,)

In [ ]:
#Split into training and testing data
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("Training samples:", X_train.shape[0])
print("Testing samples:", X_test.shape[0])

Training samples: 57600
Testing samples: 14400

In [ ]:
#Train the Random Forest Regression model
from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(
    n_estimators=100,
    random_state=42,
    n_jobs=-1
)

rf.fit(X_train, y_train)

RandomForestRegressor(n_jobs=-1, random_state=42)

In [ ]:
#Predict the model
y_pred = rf.predict(X_test)

In [ ]:
#Evaluate using MAE and RMSE
from sklearn.metrics import mean_absolute_error, mean_squared_error
import numpy as np

mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))

print("MAE:", mae)
print("RMSE:", rmse)

MAE: 44409.15949952263
RMSE: 60076.89277043019

In [ ]:
#Hyperparameter Optimization
from sklearn.model_selection import GridSearchCV

param_grid = {
    "n_estimators": [50, 100],
    "max_depth": [10, None],
    "min_samples_split": [2, 5]
}

grid_search = GridSearchCV(
    RandomForestRegressor(random_state=42, n_jobs=-1),
    param_grid,
    cv=3,
    scoring="neg_mean_squared_error",
    n_jobs=-1
)

grid_search.fit(X_train, y_train)

print("Best Parameters:", grid_search.best_params_)

In [ ]:
#Evaluate tuned model
best_rf = grid_search.best_estimator_

y_pred_tuned = best_rf.predict(X_test)

mae_tuned = mean_absolute_error(y_test, y_pred_tuned)
rmse_tuned = np.sqrt(mean_squared_error(y_test, y_pred_tuned))

print("Tuned MAE:", mae_tuned)
print("Tuned RMSE:", rmse_tuned)

In [ ]:
#Cross validation
from sklearn.model_selection import cross_val_score

cv_scores = cross_val_score(
    best_rf,
    X,
    y,
    cv=5,
    scoring="neg_mean_squared_error",
    n_jobs=-1
)

cv_rmse = np.sqrt(-cv_scores)

print("Cross-validation RMSE scores:", cv_rmse)
print("Mean CV RMSE:", cv_rmse.mean())

In [ ]:
#Error Analysis (Residual Distribution)
residuals = y_test - y_pred_tuned

import matplotlib.pyplot as plt

plt.figure(figsize=(6,4))
plt.hist(residuals, bins=30)
plt.title("Residual Error Distribution (Sydney)")
plt.xlabel("Error")
plt.ylabel("Frequency")
plt.show()

In [ ]:
#Residual Plot
plt.figure(figsize=(6,4))
plt.scatter(y_pred_tuned, residuals, alpha=0.5)
plt.axhline(0, linestyle="--")
plt.title("Residual Plot (Sydney)")
plt.xlabel("Predicted Powerall")
plt.ylabel("Residuals")
plt.show()

In [ ]:
#TASMANIA DATASET

In [ ]:
#LOAD DATASET
df_tasmania = pd.read_csv("Tasmania_Data.csv", header=None)

In [ ]:
#Assign columns
columns = (
    [f"X{i}" for i in range(1,17)] +
    [f"Y{i}" for i in range(1,17)] +
    [f"P{i}" for i in range(1,17)] +
    ["Powerall"]
)

df_tasmania.columns = columns

In [ ]:
#input and output columns
position_cols = [f"X{i}" for i in range(1,17)] + [f"Y{i}" for i in range(1,17)]
target_col = "Powerall"

X = df_tasmania[position_cols]
y = df_tasmania[target_col]

In [ ]:
#missing values
data = df_tasmania[position_cols + [target_col]].dropna()

X = data[position_cols]
y = data[target_col]

print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (72000, 32)
y shape: (72000,)

In [ ]:
#Split into training and testing data
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("Training samples:", X_train.shape[0])
print("Testing samples:", X_test.shape[0])

Training samples: 57600
Testing samples: 14400

In [ ]:
#Train the Random Forest Regression model
from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(
    n_estimators=100,
    random_state=42,
    n_jobs=-1
)

rf.fit(X_train, y_train)

RandomForestRegressor(n_jobs=-1, random_state=42)

In [ ]:
#Predict the model
y_pred = rf.predict(X_test)

In [ ]:
#Evaluate using MAE and RMSE
from sklearn.metrics import mean_absolute_error, mean_squared_error
import numpy as np

mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))

print("MAE:", mae)
print("RMSE:", rmse)

MAE: 44409.15949952263
RMSE: 60076.89277043019

In [ ]:
#Hyperparameter Tuning
from sklearn.model_selection import GridSearchCV

param_grid = {
    "n_estimators": [50, 100],
    "max_depth": [10, None],
    "min_samples_split": [2, 5]
}

grid_search = GridSearchCV(
    RandomForestRegressor(random_state=42, n_jobs=-1),
    param_grid,
    cv=3,
    scoring="neg_mean_squared_error",
    n_jobs=-1
)

grid_search.fit(X_train, y_train)

print("Best Parameters:", grid_search.best_params_)

In [ ]:
#Evaluate tuned model
best_rf = grid_search.best_estimator_

y_pred_tuned = best_rf.predict(X_test)

mae_tuned = mean_absolute_error(y_test, y_pred_tuned)
rmse_tuned = np.sqrt(mean_squared_error(y_test, y_pred_tuned))

print("Tuned MAE:", mae_tuned)
print("Tuned RMSE:", rmse_tuned)

In [ ]:
#Cross validation
from sklearn.model_selection import cross_val_score

cv_scores = cross_val_score(
    best_rf,
    X,
    y,
    cv=5,
    scoring="neg_mean_squared_error",
    n_jobs=-1
)

cv_rmse = np.sqrt(-cv_scores)

print("Cross-validation RMSE scores:", cv_rmse)
print("Mean CV RMSE:", cv_rmse.mean())

In [ ]:
#Error Analysis (Residual Distribution)
residuals = y_test - y_pred_tuned

import matplotlib.pyplot as plt

plt.figure(figsize=(6,4))
plt.hist(residuals, bins=30)
plt.title("Residual Error Distribution (Tasmania)")
plt.xlabel("Error")
plt.ylabel("Frequency")
plt.show()

In [ ]:
#Residual Plot
plt.figure(figsize=(6,4))
plt.scatter(y_pred_tuned, residuals, alpha=0.5)
plt.axhline(0, linestyle="--")
plt.title("Residual Plot (Tasmania)")
plt.xlabel("Predicted Powerall")
plt.ylabel("Residuals")
plt.show()